<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

  public function findProductLast(): array{
    $qb = $this->createQueryBuilder('p')
    ->orderBy('p.dateDerniereVue', 'desc')
    ->setMaxResults(8)
    ->getQuery();

    return $qb->execute();
  }



}
