<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

  public function findEvaluation($produit, $user){
    return $this->getEntityManager()
    ->createQuery(
        'SELECT e, u
        FROM AppBundle:Evaluation e
        JOIN e.produit u
        WHERE e.produit = :produit AND e.user = :user'
      )
      ->setParameter('produit', $produit)
      ->setParameter('user', $user)
      ->getResult();
  }
}
