<?php

namespace AppBundle\Repository;

/**
 * RepasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepasRepository extends \Doctrine\ORM\EntityRepository
{
}
